FROM alpine:3.7
MAINTAINER Nicolas Berard [berard.nicolas@gmail.com]

RUN apk add --update \
    bash \
    transmission-daemon \
    && rm -rf /var/cache/apk/*

ARG username
ARG password
ARG uid
RUN adduser -u $uid -D -h "/home/$username" $username
RUN chown $username:$username /home/$username -R
ENV username=$username
ENV password=$password
USER $username
VOLUME /home/$username
EXPOSE 9091
CMD /usr/bin/transmission-daemon -f -g /home/${username}
