FROM alpine:3.7
MAINTAINER Nicolas Berard [berard.nicolas@gmail.com]

RUN apk add --update \
    bash \
    samba-common-tools \
    samba-client \
    samba-server \
    && rm -rf /var/cache/apk/*

HEALTHCHECK --interval=60s --timeout=15s \
             CMD smbclient -L '\\localhost\' -U 'guest%'

COPY samba/add_user.sh /srv/
COPY samba/remove_user.sh /srv/

EXPOSE 445

CMD smbd --foreground --log-stdout < /dev/null
