FROM debian:7
MAINTAINER Nicolas Berard [berard.nicolas@gmail.com]

RUN apt-get update && apt-get install \
    bash \
    samba \
    && rm -rf /var/cache/apk/*

COPY samba/add_user.sh /srv/
COPY samba/remove_user.sh /srv/

EXPOSE 445

CMD smbd --foreground --log-stdout < /dev/null
