version: '3.4'

services:
  minidlna:
    image: minidlna:1.2.1
    volumes:
     - ./minidlna.conf:/etc/minidlna.conf
     - ./cache:/var/cache/minidlna
     - /home/pi/downloads:/mnt/downloads
    command: "minidlnad -r -d"
    networks: 
     - upnp
    ports:
      - target: 8200
        published: 8200
        protocol: tcp
        mode: host
      - target: 1900
        published: 1900
        protocol: udp
        mode: host
networks:
  upnp:
    external:
      name: host
